# Используем базовый образ
FROM ubuntu:20.04

# Устанавливаем SQLite
RUN apt update && apt install -y sqlite3

# Указываем рабочую директорию
WORKDIR /app

# Указываем команду по умолчанию
CMD ["sqlite3"]
